POST  /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
Content-Type: application/json

{
  "name": "a132",
  "age": 12
}

### 
POST  /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
Content-Type: application/x-www-form-urlencoded

name=a132&age=12

###
POST  /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
Content-Type: multipart/form-data; boundary=aaa

--aaa
Content-Disposition: form-data; name="name"
a132
--aaa
Content-Disposition: form-data; name="age" 
123
--aaa--
###