# This is a basic workflow to help you get started with Actions

name: deployment to github page

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "deploy"
    deploy_process:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4
              with:
                  submodules: true # Fetch Hugo themes (true OR recursive)
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  check-latest: true
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.130.0'
            - run: npm ci # clean install. remove node_modules and stick to package-lock
            - run: hugo --minify # hugo will compile as small as possible
            - name: Algolia setup
              run: ALGOLIA_APP_ID=QXEV52XWDS ALGOLIA_ADMIN_KEY=${{ secrets.ALGOLIA_ADMIN_KEY }} ALGOLIA_INDEX_NAME=blog ALGOLIA_INDEX_FILE=./public/index.json npm run algolia
            - name: gh-page setup
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: ./public
